name: toursecure
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^6.0.0
  cupertino_icons: ^1.0.8   # Optional for iOS-style icons
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  flutter_map_heatmap: ^0.0.8
  shared_preferences: ^2.2.3
  file_picker: ^8.1.2
  qr_flutter: ^4.1.0
  web3dart: ^3.0.1
  http: ^1.5.0
  intl: ^0.20.2
  share_plus: ^10.0.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/abi/TouristPass.json
