name: toursecure
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8   # Optional for iOS-style icons
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  flutter_map_heatmap: ^0.0.8
  shared_preferences: ^2.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
